---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp
  namespace: myweb
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: "pramodmadhavan/webapp"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: myweb
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 80
    nodePort:31004
